services:
  strapi:
    container_name: portfolio-cms-dev
    build:
      context: ../../apps/cms
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    image: portfolio-cms:dev
    restart: unless-stopped

    env_file:
      - ./.env

    environment:
      NODE_ENV: development
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}

      HOST: ${HOST}
      PORT: ${PORT}

    ports:
      - "1337:1337"

    volumes:
      - ../../apps/cms/config:/opt/app/config
      - ../../apps/cms/src:/opt/app/src
      - ../../apps/cms/public:/opt/app/public
      - ../../apps/cms/package.json:/opt/app/package.json
      - ../../apps/cms/pnpm-lock.yaml:/opt/app/pnpm-lock.yaml
      - ../../apps/cms/tsconfig.json:/opt/app/tsconfig.json

      # Persistir uploads (recomendado)
      - strapi_uploads:/opt/app/public/uploads

      # (Opcional) caches
      - strapi_cache:/opt/app/.cache
      - strapi_tmp:/opt/app/.tmp

    depends_on:
      strapiDB:
        condition: service_healthy

  strapiDB:
    container_name: portfolio-postgres-dev
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - strapi-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  strapi-data:
  strapi_node_modules:
  strapi_uploads:
  strapi_cache:
  strapi_tmp:
